import { profile, projects, skills, education, certifications } from './content.mjs';

export const escape = (text) => String(text).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const arrow = '<span aria-hidden="true">↗</span>';
export const external = (url, text, cls = '') => `<a class="${cls}" href="${escape(url)}" target="_blank" rel="noopener noreferrer">${text} ${arrow}<span class="sr-only"> (opens in a new tab)</span></a>`;
const tagList = items => `<ul class="tags" aria-label="Technologies">${items.map(t => `<li>${escape(t)}</li>`).join('')}</ul>`;
const label = (number, title) => `<p class="eyebrow"><span>${number}</span> ${title}</p>`;
const heading = (number, title, subtitle) => `<div class="section-heading">${label(number, title)}<h2>${subtitle}</h2></div>`;

export function Header() {
  return `<a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="shell header-inner"><a class="brand" href="#home" aria-label="Sandeep Yadav, home"><span class="brand-mark" aria-hidden="true">sy<span>.</span></span><span>Sandeep Yadav</span></a><nav aria-label="Main navigation" id="main-nav"><a href="#about">About</a><a href="#projects">Projects</a><a href="#skills">Skills</a><a href="#experience">Experience</a><a href="#education">Education</a><a href="#certifications">Certifications</a><a href="#contact">Contact</a></nav><div class="header-actions"><button class="icon-button theme-toggle" type="button" aria-label="Switch to dark theme" hidden><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="M20.5 13.2A8.5 8.5 0 0 1 10.8 3.5a8.5 8.5 0 1 0 9.7 9.7Z"/></svg></button><button class="menu-toggle" type="button" aria-controls="main-nav" aria-expanded="false" hidden>Menu <span aria-hidden="true">☰</span></button></div></div></header>`;
}

export function Hero() {
 return `<section class="hero shell" id="home" aria-labelledby="hero-title"><div class="hero-copy"><p class="availability"><span aria-hidden="true"></span>Seeking an entry-level developer role</p><p class="hero-name">Hello, I’m Sandeep.</p><h1 id="hero-title">Software developer.<br><span>Backend focused.</span></h1><p class="hero-description">I build database-backed applications with Java, Python, and TypeScript—from reliable background job processing to full-stack collaboration tools.</p><div class="cta-row"><a class="button primary" href="#projects">Explore my projects <span aria-hidden="true">↘</span></a><a class="button secondary" href="${profile.resume}" download>Download resume <span aria-hidden="true">↓</span></a></div><div class="hero-links">${external(profile.github, 'GitHub')}${external(profile.linkedin, 'LinkedIn')}<a href="#contact">Get in touch <span aria-hidden="true">↗</span></a></div><p class="location"><span aria-hidden="true">⌖</span> Varanasi, Uttar Pradesh, India <span class="location-divider">/</span> B.Tech IT, 2025</p></div><aside class="hero-system" aria-label="JobFlow architecture overview"><div class="system-top"><span class="tiny-square" aria-hidden="true"></span><span>PROJECT SPOTLIGHT</span><span class="system-version">01 / 03</span></div><div class="system-title"><h2>JobFlow</h2><p>Durable work. Deliberate recovery.</p></div><div class="architecture"><div class="architecture-node"><span class="node-icon" aria-hidden="true">↳</span><div><strong>REST API</strong><small>JWT auth · idempotent submission</small></div><code>POST /api/jobs</code></div><div class="connector" aria-hidden="true">↓</div><div class="architecture-node database"><span class="node-icon" aria-hidden="true">≋</span><div><strong>PostgreSQL</strong><small>Durable queue · atomic claims</small></div><span class="node-status">PERSIST</span></div><div class="connector" aria-hidden="true">↕</div><div class="architecture-node"><span class="node-icon" aria-hidden="true">⌘</span><div><strong>Worker pool</strong><small>Leases · retries · crash recovery</small></div><span class="node-status">EXECUTE</span></div><div class="outcome-row"><span>Completed</span><span>Retry wait</span><span>Dead letter</span></div></div><div class="system-bottom"><span>Architecture overview · from the source</span><a href="#project-jobflow" aria-label="Read JobFlow case study">Read case study ↗</a></div></aside></section><div class="focus-strip"><div class="shell"><span class="eyebrow">PRIMARY TOOLKIT</span><span>Java</span><span>Spring Boot</span><span>Python</span><span>FastAPI</span><span>PostgreSQL</span><span>React</span></div></div>`;
}

export function About() {
 return `<section class="section shell about-layout" id="about">${heading('01', 'ABOUT ME', 'A practical approach<br>to building software.')}<div class="about-copy"><p class="lead">I’m an Information Technology graduate from Ajay Kumar Garg Engineering College, with hands-on project experience in backend systems, full-stack applications, and Python computer vision.</p><p>My work centers on how applications handle data and state: consistent database transactions, authenticated APIs, and background work that can recover from failure. I use Java and Python on the backend and React with TypeScript for application interfaces.</p><p>I’m looking for an entry-level software development role where I can contribute to a team, deepen my engineering skills, and build useful software.</p><div class="about-foot"><span>Java & Python backends</span><span>Database-backed applications</span><span>Full-stack development</span></div></div></section>`;
}

function CaseStudy(project) {
 return `<details class="case-study" id="case-${project.id}"><summary>Implementation & design decisions <span aria-hidden="true">+</span></summary><div class="case-body"><h4>The problem</h4><p>${escape(project.problem)}</p><h4>What I implemented</h4><ul>${project.implementation.map(x=>`<li>${escape(x)}</li>`).join('')}</ul><h4>Design trade-offs</h4><p>${escape(project.tradeoff)}</p><p class="evidence-note">${escape(project.evidence)}</p>${external(project.source,project.sourceLabel,'text-link')}</div></details>`;
}

export function Projects() {
 return `<section class="section projects-section" id="projects"><div class="shell"><div class="project-section-header">${heading('02', 'SELECTED WORK', 'Built to solve.<br>Open to inspect.')}<div class="projects-intro"><p>A closer look at the code, implementation decisions, and trade-offs behind my work.</p><div class="project-filters" role="group" aria-label="Filter projects" hidden><button type="button" data-filter="All" aria-pressed="true">All work</button><button type="button" data-filter="Backend" aria-pressed="false">Backend</button><button type="button" data-filter="Full-stack" aria-pressed="false">Full-stack</button></div></div></div><p class="sr-only" id="filter-status" role="status"></p><div class="project-list">${projects.map(p=>`<article class="project-card ${p.id==='jobflow'?'featured':''}" data-category="${p.category}" id="project-${p.id}"><div class="project-index"><span>${p.number}</span><span class="project-category">${p.category}</span></div><div class="project-main"><p class="eyebrow">${p.id==='jobflow'?'FEATURED PROJECT':escape(p.subtitle)}</p><h3>${p.name}</h3><p class="project-description">${p.description}</p>${tagList(p.technologies)}<div class="project-links">${external(p.repository,'View repository','text-link')}${p.demo?external(p.demo,'Live application','text-link'):''}</div>${CaseStudy(p)}</div><div class="project-side">${p.id==='jobflow'?`<p class="code-label">THE COORDINATION PRIMITIVE</p><pre aria-label="Excerpt of the PostgreSQL job-claim query"><code><span>SELECT</span> id <span>FROM</span> jobs
<span>WHERE</span> status <span>IN</span>
  ('QUEUED', 'RETRY_WAIT')
<span>AND</span> available_at
  &lt;= clock_timestamp()
<em>…</em>
<span>FOR UPDATE SKIP LOCKED</span>
<span>LIMIT</span> 1</code></pre><p class="side-caption">One transaction claims the next eligible job. Other workers skip locked rows.</p>`:p.id==='devhub'?`<p class="code-label">WORKSPACE STRUCTURE</p><div class="workspace-stack"><div>Organization <small>Roles & membership</small></div><div>Private project <small>Access grants</small></div><div>Tasks & discussions <small>Versioning & replies</small></div></div><p class="side-caption">A source-based overview of the collaboration model.</p>`:`<p class="code-label">SEPARATION OF CONCERNS</p><div class="layer-stack"><span>BookingService</span><span>BookingRepository</span><div><span>In-memory</span><span>MySQL / JDBC</span></div></div><p class="side-caption">One service layer. Two persistence implementations.</p>`}</div></article>`).join('')}</div><div class="more-work"><p>More experiments in data, analytics, and development.</p><div class="more-links">${external('https://sandii087.github.io/','Data analytics portfolio','text-link')}${external(profile.github+'?tab=repositories','All repositories','text-link')}</div></div></div></section>`;
}

export function Skills() {
 return `<section class="section shell" id="skills">${heading('03', 'TECHNICAL SKILLS', 'The tools behind the work.')}<div class="skills-grid">${skills.map((s,i)=>`<div class="skill-group"><span class="skill-index">0${i+1}</span><h3>${s.name}</h3>${tagList(s.items)}</div>`).join('')}</div></section>`;
}

export function Experience() {
 return `<section class="section experience-section" id="experience"><div class="shell experience-layout">${heading('04', 'EXPERIENCE', 'Learning through<br>implementation.')}<div><p class="experience-intro">My experience so far is project-based, with a focus on backend reliability, application development, and data handling.</p><ol class="timeline"><li><span class="timeline-label">BACKEND SYSTEMS</span><h3>Asynchronous processing & transactional data</h3><p>Implemented durable queues, job recovery, and authenticated APIs in JobFlow; explored transactional seat booking and repository design in Java.</p><a href="#project-jobflow" class="text-link">Explore JobFlow <span aria-hidden="true">↗</span></a></li><li><span class="timeline-label">FULL-STACK APPLICATIONS</span><h3>Developer collaboration workflows</h3><p>Built the interface and API layers for organizations, projects, tasks, and discussions, with access controls and automated tests.</p><a href="#project-devhub" class="text-link">Explore DevHub AI <span aria-hidden="true">↗</span></a></li><li><span class="timeline-label">DATA & APPLIED LEARNING</span><h3>Python, SQL & supervised learning</h3><p>Worked with data handling, feature engineering, and sales prediction through AI Fundamentals, alongside SQL and data-science coursework.</p><a href="#certifications" class="text-link">View certifications <span aria-hidden="true">↗</span></a></li></ol></div></div></section>`;
}

export function Education() {
 return `<section class="section shell" id="education">${heading('05', 'EDUCATION', 'A foundation in technology.')}<div class="education-list">${education.map(e=>`<article class="education-card"><p class="education-date">${e.period}</p><div><h3>${e.name}</h3><p>${e.school}</p>${external(e.url,e.label,'text-link')}</div><strong class="education-result">${e.result}</strong></article>`).join('')}</div></section>`;
}

export function Certifications() {
 return `<section class="section shell certifications-section" id="certifications">${heading('06', 'CERTIFICATIONS', 'Continued learning.')}<div class="cert-grid">${certifications.map((c,i)=>`<article class="cert-card"><div class="cert-top"><span class="certificate-symbol" aria-hidden="true">▤</span><time datetime="${['2026-03','2024-10','2024-03'][i]}">${c.date}</time></div><h3>${external(c.url,c.name)}</h3><p class="cert-issuer">${c.issuer}</p>${c.description?`<p class="cert-description">${c.description}</p>`:''}<span class="cert-bottom">View certificate <span aria-hidden="true">↗</span></span></article>`).join('')}</div></section>`;
}

export function Contact() {
 return `<section class="contact-section" id="contact"><div class="shell contact-layout"><div>${label('07','GET IN TOUCH')}<h2>Let’s build<br>something useful.</h2><p>I’m seeking entry-level software and backend development opportunities. Have a role or a project in mind? I’d be glad to connect.</p><a class="button primary" href="mailto:${profile.email}">Email Sandeep <span aria-hidden="true">↗</span></a></div><address class="contact-details"><div><span>EMAIL</span><a href="mailto:${profile.email}">${profile.email}</a></div><div><span>PHONE</span><a href="${profile.telephone}">${profile.phone}</a></div><div><span>BASED IN</span><p>${profile.location}, India</p></div><div class="contact-social">${external(profile.github,'GitHub')}${external(profile.linkedin,'LinkedIn')}</div></address></div></section>`;
}

export function Footer() {
 return `<footer class="site-footer"><div class="shell"><a class="brand" href="#home"><span class="brand-mark" aria-hidden="true">sy<span>.</span></span><span>Sandeep Yadav</span></a><p>Software development · Backend systems · Full-stack applications</p><a href="#home">Back to top <span aria-hidden="true">↑</span></a></div></footer>`;
}
