import { Header, Hero, About, Projects, Skills, Experience, Education, Certifications, Contact, Footer, escape } from './components.mjs';
import { profile } from './content.mjs';

export function renderPage(siteUrl = '') {
  const title = 'Sandeep Yadav | Software Developer · Backend & Full-stack';
  const description = 'Sandeep Yadav is an Information Technology graduate building Java, Spring Boot, Python, FastAPI, and React applications. Explore JobFlow, DevHub AI, and transactional Java projects.';
  const canonical = siteUrl ? `${siteUrl.replace(/\/$/, '')}/` : '';
  const schema = { '@context': 'https://schema.org', '@type': 'Person', name: profile.name, description, email: profile.email, sameAs: [profile.github, profile.linkedin], alumniOf: { '@type': 'CollegeOrUniversity', name: 'Ajay Kumar Garg Engineering College' }, ...(canonical ? {url: canonical} : {}) };
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light dark"><meta name="theme-color" content="#f7f8f5"><title>${title}</title><meta name="description" content="${description}"><meta name="author" content="Sandeep Yadav"><meta property="og:type" content="website"><meta property="og:title" content="${title}"><meta property="og:description" content="${description}"><meta property="og:locale" content="en_IN"><meta name="twitter:card" content="summary_large_image">${canonical?`<link rel="canonical" href="${escape(canonical)}"><meta property="og:url" content="${escape(canonical)}"><meta property="og:image" content="${escape(canonical)}assets/social-card.png"><meta name="twitter:image" content="${escape(canonical)}assets/social-card.png">`:''}<meta property="og:image:alt" content="Sandeep Yadav — software developer, backend and full-stack"><link rel="icon" href="./assets/favicon.svg" type="image/svg+xml"><link rel="apple-touch-icon" href="./assets/apple-touch-icon.png"><link rel="stylesheet" href="./styles.css"><script src="./theme.js"></script><script type="module" src="./main.js"></script><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script></head><body>${Header()}<main id="main" tabindex="-1">${Hero()}${About()}${Projects()}${Skills()}${Experience()}${Education()}${Certifications()}${Contact()}</main>${Footer()}</body></html>`;
}
